version: '3'
services:
    mysql56-slave-galaxy1:
        image: mysql:5.6
        restart: always
        container_name: mysql56-slave-galaxy1
        environment:
            MYSQL_ROOT_PASSWORD: test100test
        ports:
            - "3306:3306"
        volumes:
           mysql56-slave-galaxy1:/var/lib/mysql
           ./slave.cnf:/etc/mysql/my.cnf
        network:
         - mysql
volumes:
  mysql56-slave-galaxy1:
network:
   mysql:
  